language: ruby
rvm:
- 1.9.3
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rake --trace db:migrate
before_deploy:
- heroku pgbackups:capture --expire --app keventer-test HEROKU_POSTGRESQL_COPPER_URL
deploy:
  provider: heroku
  api_key:
    secure: KLy58hugX51Nq+QcX8UEBt1tZN6KSgif2w1QEeDjdvddrsiIXugISXkh7VvTVbg0gLXVbYiHBKaguAySTPBpJL6bdMWygcepAlMJNnlF44q86IwpzGg+eaMzNjbtt2NZo9RIAfbofu/13ckHNgTTGSZo+0MArQG4HUYGyy5KLbs=
  app:
    develop: keventer-test
    master: keventer